### PR TITLE
Bump to 440.82

### PR DESCRIPTION
**Pull request by Aaahh**

### CODE REVIEW

**Comment by tofurky** [comment]
thanks, however 440.82 was just released in the ubuntu ppa a few hours ago.

**Comment by Aaahh** [comment]
Bruh

**Comment by tofurky** [comment]
could you please squash the two commits into a single one for 440.82, then i can merge. thanks.

something like 'git rebase -i HEAD~2' then push --force origin master, or however you want to do it.

i don't have the option to squash them here.

**Comment by tofurky** [comment]
actually, it looks like i can squash them. thanks!

**Pull request merged**
