### PR TITLE
Added support for 470.x

### PR DESCRIPTION
**Pull request by PM1001**
Tested on 1 system, so please test before merging.

### CODE REVIEW

**Comment by tofurky** [comment]
thanks for the PR.

it looks OK as-is, but 470 is still in beta. i would like to wait until it's officially released before merging and making it the default.

can we leave this PR pending and update the README.md/Makefile to the final release version when it's available? then merge to master.

**Comment by PM1001** [comment]
That makes sense. I did not realize the drivers are still in beta.

**Comment by tofurky** [comment]
yeah, i am not sure when the final release will be
image

**Comment by PM1001** [comment]
Hmmm, that is strange, if I select production branch, I get this:
image
And if I click on "new feature branch" it gives me v465.

**Comment by tofurky** [comment]
cool, it looks like it was actually released in the past 24 hrs.

can you please update the PR from 470.42.01 to 470.57.02? probably some quick testing should be done to confirm that the offsets are the same (i have seen them change between the "same" version at least once on 450.x, see below https://github.com/CFSworks/nvml_fix/blob/fe4e87bf8c1e9580c6cae81ece5c921941eb35da/nvml_fix.c#L114-L125)

then i will merge

https://www.gamingonlinux.com/2021/07/nvidia-4705702-released-as-the-next-stable-linux-driver

**Comment by PM1001** [comment]
Ok, let me see if I can update my driver to 470.57 without breaking anything.

**Comment by PM1001** [comment]
Ok, I have made the changes and verified that the offsets still work with 470.57.02 on my system.

**Comment by tofurky** [comment]
thanks, merged

**Pull request merged**
